import React, { useState, useEffect, useRef } from 'react';
import { Patient, User, HealthUnit } from '../types';
import { api } from '../services/api';
import { Plus, Search, User as UserIcon, Users as UsersIcon, Download, MapPin, FileText, Edit2, Upload, Trash2, X, AlertCircle } from 'lucide-react';
import { buscarCEP, validarCNS, formatCEP } from '../src/utils/validators';

export const Patients: React.FC = () => {
  const [user, setUser] = useState<User | null>(null);
  const [patients, setPatients] = useState<Patient[]>([]);
  const [searchTerm, setSearchTerm] = useState('');
  const [viewMode, setViewMode] = useState<'list' | 'form'>('list');
  const [editingId, setEditingId] = useState<string | null>(null);
  const [formData, setFormData] = useState<Partial<Patient>>({});
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [isImporting, setIsImporting] = useState(false);
  const [isImportModalOpen, setIsImportModalOpen] = useState(false);
  const [units, setUnits] = useState<HealthUnit[]>([]);

  useEffect(() => {
    const loadPatients = async () => {
      const stored = localStorage.getItem('health_user');
      if (stored) {
        const u = JSON.parse(stored);
        setUser(u);
        setFormData({ unitId: u.unitId });
        
        try {
          const [fetchedPatients, fetchedUnits] = await Promise.all([
            api.patients.getByUnit(u.unitId),
            api.units.getAll()
          ]);
          setPatients(fetchedPatients);
          setUnits(fetchedUnits);
        } catch (error) {
          console.error("Erro ao carregar dados:", error);
        }
      }
    };
    loadPatients();
  }, []);

  const resetForm = () => {
      setFormData({ unitId: user?.unitId });
      setEditingId(null);
  };

  const handleEdit = (p: Patient) => {
      setEditingId(p.id);
      setFormData(p);
      setViewMode('form');
  };

  const handleSavePatient = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!user) return;

    if (formData.susNumber && !validarCNS(formData.susNumber)) {
        alert('O número do Cartão SUS (CNS) informado é inválido. Por favor, verifique.');
        return;
    }

    if (!formData.unitIds?.length && !formData.unitId) {
        alert('Por favor, selecione pelo menos uma unidade de referência.');
        return;
    }

    if (editingId) {
        api.patients.update(editingId, formData);
    } else {
        const patientToAdd = { ...formData, unitId: user.unitId } as Patient;
        api.patients.add(patientToAdd);
    }

    const patients = await api.patients.getByUnit(user.unitId);
    setPatients(patients);
    setViewMode('list');
    resetForm();
  };

  const handleDelete = async (patient: Patient) => {
      if (window.confirm(`Tem certeza que deseja remover o paciente ${patient.name}?`)) {
          await api.patients.delete(patient.id);
          if (user) {
              const updatedPatients = await api.patients.getByUnit(user.unitId);
              setPatients(updatedPatients);
          }
      }
  };

  const handleDownloadTemplate = () => {
    const headers = ['Nome', 'CPF', 'Cartão SUS', 'Data de Nascimento', 'Telefone', 'Endereço'];
    const csvContent = headers.join(',') + '\n"João Silva","123.456.789-00","700000000000000","2000-01-01","(00) 00000-0000","Rua Exemplo, 123"';
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', 'modelo_importacao_pacientes.csv');
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file || !user) return;
    
    setIsImporting(true);
    const reader = new FileReader();
    reader.onload = async (event) => {
        const text = event.target?.result as string;
        const lines = text.split('\n');
        
        let importedCount = 0;
        
        // Skipping header (lines[0])
        for (let i = 1; i < lines.length; i++) {
            const line = lines[i].trim();
            if (!line) continue;
            
            // Assuming format: Nome, CPF, Cartão SUS, Data de Nascimento, Telefone, Endereço
            const columns = line.split(',');
            if (columns.length >= 2) {
                const newPatient: Patient = {
                    id: '', // Will be generated by API
                    name: columns[0].trim(),
                    cpf: columns[1].trim(),
                    susNumber: columns[2] ? columns[2].trim() : undefined,
                    birthDate: columns[3] ? columns[3].trim() : '2000-01-01',
                    phone: columns[4] ? columns[4].trim() : '(00) 00000-0000',
                    address: columns[5] ? columns[5].trim() : undefined,
                    unitId: user.unitId
                };
                
                await api.patients.add(newPatient);
                importedCount++;
            }
        }
        
        if (fileInputRef.current) fileInputRef.current.value = '';
        const updatedPatients = await api.patients.getByUnit(user.unitId);
        setPatients(updatedPatients);
        setIsImporting(false);
        setIsImportModalOpen(false);
        alert(`${importedCount} pacientes importados com sucesso!`);
    };
    reader.readAsText(file);
  };

  const handleExport = () => {
    const headers = ['Nome', 'CPF', 'SUS', 'Telefone', 'Nascimento', 'Endereço', 'Bairro'];
    const csvContent = [
      headers.join(','),
      ...patients.map(p => [
        `"${p.name}"`,
        `"${p.cpf}"`,
        `"${p.susNumber || ''}"`,
        `"${p.phone}"`,
        `"${p.birthDate}"`,
        `"${p.address || ''}"`,
        `"${p.neighborhood || ''}"`
      ].join(','))
    ].join('\n');

    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', 'pacientes_export.csv');
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const filteredPatients = patients.filter(p => 
    p.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
    p.cpf.includes(searchTerm) ||
    (p.susNumber && p.susNumber.includes(searchTerm))
  );

  // Mask Utilities
  const maskCPF = (value: string) => {
    return value
      .replace(/\D/g, '')
      .replace(/(\d{3})(\d)/, '$1.$2')
      .replace(/(\d{3})(\d)/, '$1.$2')
      .replace(/(\d{3})(\d{1,2})/, '$1-$2')
      .replace(/(-\d{2})\d+?$/, '$1');
  };

  const maskPhone = (value: string) => {
    return value
      .replace(/\D/g, '')
      .replace(/(\d{2})(\d)/, '($1) $2')
      .replace(/(\d{5})(\d)/, '$1-$2')
      .replace(/(-\d{4})\d+?$/, '$1');
  };

  const handleInputChange = (field: keyof Patient, value: string) => {
     let formattedValue = value;
     if (field === 'cpf') formattedValue = maskCPF(value);
     if (field === 'phone') formattedValue = maskPhone(value);
     setFormData({...formData, [field]: formattedValue});
  };

  const handleCepBlur = async () => {
      if (formData.cep && formData.cep.replace(/\D/g, '').length === 8) {
          const data = await buscarCEP(formData.cep);
          if (data) {
              setFormData(prev => ({
                  ...prev,
                  address: data.logradouro,
                  neighborhood: data.bairro,
                  city: data.localidade,
                  state: data.uf
              }));
          }
      }
  };

  if (!user) return null;

  if (viewMode === 'form') {
    return (
      <div className="space-y-6 pb-12 animate-in fade-in slide-in-from-bottom-4 duration-500">
        <div className="flex justify-between items-center pb-4 border-b border-slate-200 dark:border-slate-800">
          <div>
            <h2 className="text-2xl font-bold text-slate-800 dark:text-slate-100">Cadastro de Paciente</h2>
            <p className="text-sm text-slate-500 dark:text-slate-400 mt-1 flex items-center gap-2">
              <span className="hover:text-primary cursor-pointer transition-colors" onClick={() => setViewMode('list')}>Pacientes</span> 
              <span>&gt;</span> 
              <span className="font-semibold text-slate-700 dark:text-slate-300">Cadastro de Paciente</span>
            </p>
          </div>
        </div>

        <form onSubmit={handleSavePatient} className="flex flex-col lg:flex-row gap-8">
            {/* Coluna Esquerda (Formulário Principal) */}
            <div className="flex-1 space-y-8">
                {/* Dados Pessoais */}
                <div className="bg-white dark:bg-slate-950 p-6 md:p-8 rounded-2xl shadow-sm border border-slate-200 dark:border-slate-800 transition-colors">
                    <h3 className="text-lg font-bold text-primary dark:text-blue-400 mb-6 flex items-center gap-2">
                        <UserIcon className="w-5 h-5" />
                        Dados pessoais
                    </h3>
                    <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
                        <div className="md:col-span-2">
                            <label className="block text-sm font-semibold text-slate-700 dark:text-slate-300 mb-2">Nome completo <span className="text-red-500">*</span></label>
                            <input required className="w-full p-3 border border-slate-300 dark:border-slate-700 rounded-xl bg-slate-50 dark:bg-slate-900 text-slate-900 dark:text-slate-100 focus:ring-2 focus:ring-primary focus:bg-white transition-all outline-none" placeholder="Digite o nome completo do paciente" value={formData.name || ''} onChange={e => handleInputChange('name', e.target.value)} />
                        </div>
                        <div>
                            <label className="block text-sm font-semibold text-slate-700 dark:text-slate-300 mb-2">RG</label>
                            <input className="w-full p-3 border border-slate-300 dark:border-slate-700 rounded-xl bg-slate-50 dark:bg-slate-900 text-slate-900 dark:text-slate-100 focus:ring-2 focus:ring-primary focus:bg-white transition-all outline-none" placeholder="Digite o RG" value={formData.rg || ''} onChange={e => handleInputChange('rg', e.target.value)} />
                        </div>
                        <div>
                            <label className="block text-sm font-semibold text-slate-700 dark:text-slate-300 mb-2">CPF <span className="text-red-500">*</span></label>
                            <input required maxLength={14} className="w-full p-3 border border-slate-300 dark:border-slate-700 rounded-xl bg-slate-50 dark:bg-slate-900 text-slate-900 dark:text-slate-100 focus:ring-2 focus:ring-primary focus:bg-white transition-all outline-none" placeholder="000.000.000-00" value={formData.cpf || ''} onChange={e => handleInputChange('cpf', e.target.value)} />
                        </div>
                        
                        <div className="md:col-span-2">
                            <label className="block text-sm font-semibold text-slate-700 dark:text-slate-300 mb-2">Número do Cartão do SUS <span className="text-red-500">*</span></label>
                            <input required className="w-full p-3 border border-slate-300 dark:border-slate-700 rounded-xl bg-slate-50 dark:bg-slate-900 text-slate-900 dark:text-slate-100 focus:ring-2 focus:ring-primary focus:bg-white transition-all outline-none" placeholder="0000 0000 0000 0000" value={formData.susNumber || ''} onChange={e => handleInputChange('susNumber', e.target.value)} />
                        </div>
                        <div>
                            <label className="block text-sm font-semibold text-slate-700 dark:text-slate-300 mb-2">Data de nascimento <span className="text-red-500">*</span></label>
                            <input required type="date" className="w-full p-3 border border-slate-300 dark:border-slate-700 rounded-xl bg-slate-50 dark:bg-slate-900 text-slate-900 dark:text-slate-100 focus:ring-2 focus:ring-primary focus:bg-white transition-all outline-none" value={formData.birthDate || ''} onChange={e => handleInputChange('birthDate', e.target.value)} />
                        </div>
                        <div>
                            <label className="block text-sm font-semibold text-slate-700 dark:text-slate-300 mb-2">Sexo <span className="text-red-500">*</span></label>
                            <select required className="w-full p-3 border border-slate-300 dark:border-slate-700 rounded-xl bg-slate-50 dark:bg-slate-900 text-slate-900 dark:text-slate-100 focus:ring-2 focus:ring-primary focus:bg-white transition-all outline-none" value={formData.gender || ''} onChange={e => handleInputChange('gender', e.target.value)}>
                                <option value="">Selecione o sexo</option>
                                <option value="Masculino">Masculino</option>
                                <option value="Feminino">Feminino</option>
                                <option value="Outro">Outro</option>
                            </select>
                        </div>

                        <div className="md:col-span-2">
                            <label className="block text-sm font-semibold text-slate-700 dark:text-slate-300 mb-2">Telefone <span className="text-red-500">*</span></label>
                            <input required maxLength={15} className="w-full p-3 border border-slate-300 dark:border-slate-700 rounded-xl bg-slate-50 dark:bg-slate-900 text-slate-900 dark:text-slate-100 focus:ring-2 focus:ring-primary focus:bg-white transition-all outline-none" placeholder="(00) 00000-0000" value={formData.phone || ''} onChange={e => handleInputChange('phone', e.target.value)} />
                        </div>
                        <div className="md:col-span-2">
                            <label className="block text-sm font-semibold text-slate-700 dark:text-slate-300 mb-2">E-mail</label>
                            <input type="email" className="w-full p-3 border border-slate-300 dark:border-slate-700 rounded-xl bg-slate-50 dark:bg-slate-900 text-slate-900 dark:text-slate-100 focus:ring-2 focus:ring-primary focus:bg-white transition-all outline-none" placeholder="email@exemplo.com" value={formData.email || ''} onChange={e => handleInputChange('email', e.target.value)} />
                        </div>
                    </div>
                </div>

                {/* Endereço */}
                <div className="bg-white dark:bg-slate-950 p-6 md:p-8 rounded-2xl shadow-sm border border-slate-200 dark:border-slate-800 transition-colors">
                    <h3 className="text-lg font-bold text-primary dark:text-blue-400 mb-6 flex items-center gap-2">
                        <MapPin className="w-5 h-5" />
                        Endereço
                    </h3>
                    <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
                        <div>
                            <label className="block text-sm font-semibold text-slate-700 dark:text-slate-300 mb-2">CEP <span className="text-red-500">*</span></label>
                            <div className="relative">
                                <input required className="w-full p-3 pr-10 border border-slate-300 dark:border-slate-700 rounded-xl bg-slate-50 dark:bg-slate-900 text-slate-900 dark:text-slate-100 focus:ring-2 focus:ring-primary focus:bg-white transition-all outline-none" placeholder="00000-000" maxLength={9} value={formData.cep || ''} onChange={e => handleInputChange('cep', formatCEP(e.target.value))} onBlur={handleCepBlur} />
                                <Search className="absolute right-3 top-3.5 w-5 h-5 text-slate-400 cursor-pointer hover:text-primary" />
                            </div>
                        </div>
                        <div className="md:col-span-2">
                            <label className="block text-sm font-semibold text-slate-700 dark:text-slate-300 mb-2">Endereço <span className="text-red-500">*</span></label>
                            <input required className="w-full p-3 border border-slate-300 dark:border-slate-700 rounded-xl bg-slate-50 dark:bg-slate-900 text-slate-900 dark:text-slate-100 focus:ring-2 focus:ring-primary focus:bg-white transition-all outline-none" placeholder="Digite o endereço" value={formData.address || ''} onChange={e => handleInputChange('address', e.target.value)} />
                        </div>
                        <div>
                            <label className="block text-sm font-semibold text-slate-700 dark:text-slate-300 mb-2 flex items-center justify-between">
                                <span>Número <span className="text-red-500">*</span></span>
                                <label className="flex items-center gap-1 text-xs font-normal text-slate-500 cursor-pointer">
                                  <input type="checkbox" className="rounded border-slate-300 text-primary focus:ring-primary" checked={formData.addressNumber === 'S/N'} onChange={e => handleInputChange('addressNumber', e.target.checked ? 'S/N' : '')} />
                                  S/N
                                </label>
                            </label>
                            <input required disabled={formData.addressNumber === 'S/N'} className="w-full p-3 border border-slate-300 dark:border-slate-700 rounded-xl bg-slate-50 dark:bg-slate-900 text-slate-900 dark:text-slate-100 focus:ring-2 focus:ring-primary focus:bg-white transition-all outline-none disabled:opacity-50" placeholder="Número" value={formData.addressNumber || ''} onChange={e => handleInputChange('addressNumber', e.target.value)} />
                        </div>

                        <div>
                            <label className="block text-sm font-semibold text-slate-700 dark:text-slate-300 mb-2">Bairro <span className="text-red-500">*</span></label>
                            <input required className="w-full p-3 border border-slate-300 dark:border-slate-700 rounded-xl bg-slate-50 dark:bg-slate-900 text-slate-900 dark:text-slate-100 focus:ring-2 focus:ring-primary focus:bg-white transition-all outline-none" placeholder="Digite o bairro" value={formData.neighborhood || ''} onChange={e => handleInputChange('neighborhood', e.target.value)} />
                        </div>
                        <div className="md:col-span-1">
                            <label className="block text-sm font-semibold text-slate-700 dark:text-slate-300 mb-2">Cidade <span className="text-red-500">*</span></label>
                            <input required className="w-full p-3 border border-slate-300 dark:border-slate-700 rounded-xl bg-slate-50 dark:bg-slate-900 text-slate-900 dark:text-slate-100 focus:ring-2 focus:ring-primary focus:bg-white transition-all outline-none" placeholder="Cidade" value={formData.city || ''} onChange={e => handleInputChange('city', e.target.value)} />
                        </div>
                        <div className="md:col-span-1">
                            <label className="block text-sm font-semibold text-slate-700 dark:text-slate-300 mb-2">Estado <span className="text-red-500">*</span></label>
                            <input required className="w-full p-3 border border-slate-300 dark:border-slate-700 rounded-xl bg-slate-50 dark:bg-slate-900 text-slate-900 dark:text-slate-100 focus:ring-2 focus:ring-primary focus:bg-white transition-all outline-none" placeholder="UF" maxLength={2} value={formData.state || ''} onChange={e => handleInputChange('state', e.target.value.toUpperCase())} />
                        </div>
                        <div className="md:col-span-2">
                            <label className="block text-sm font-semibold text-slate-700 dark:text-slate-300 mb-2">Unidades de referência <span className="text-red-500">*</span></label>
                            <div className="w-full max-h-48 overflow-y-auto p-2 border border-slate-300 dark:border-slate-700 rounded-xl bg-slate-50 dark:bg-slate-900 flex flex-col gap-1 transition-all">
                                {units.map(unit => {
                                    const isSelected = (formData.unitIds || (formData.unitId ? [formData.unitId] : [])).includes(unit.id);
                                    return (
                                        <label key={unit.id} className={`flex items-center gap-3 cursor-pointer p-2.5 rounded-lg transition-colors border ${isSelected ? 'bg-blue-50/50 border-blue-200 dark:bg-blue-900/20 dark:border-blue-800' : 'border-transparent hover:bg-slate-100 dark:hover:bg-slate-800'}`}>
                                            <input 
                                                type="checkbox" 
                                                className="w-4 h-4 rounded border-slate-300 text-primary focus:ring-primary dark:border-slate-600 dark:bg-slate-700 cursor-pointer" 
                                                checked={isSelected}
                                                onChange={(e) => {
                                                    let currentIds = formData.unitIds || (formData.unitId ? [formData.unitId] : []);
                                                    if (e.target.checked) {
                                                        currentIds = [...currentIds, unit.id];
                                                    } else {
                                                        currentIds = currentIds.filter(id => id !== unit.id);
                                                    }
                                                    setFormData({...formData, unitIds: currentIds, unitId: currentIds[0]});
                                                }}
                                            />
                                            <span className={`text-sm font-medium ${isSelected ? 'text-primary dark:text-blue-400' : 'text-slate-700 dark:text-slate-300'}`}>
                                                {unit.name} {unit.cnesCode ? <span className="text-slate-400 text-xs font-normal">({unit.cnesCode})</span> : ''}
                                            </span>
                                        </label>
                                    );
                                })}
                                {units.length === 0 && (
                                    <div className="text-sm text-slate-500 p-2 text-center">Nenhuma unidade disponível</div>
                                )}
                            </div>
                            {(!formData.unitIds?.length && !formData.unitId) && (
                                <p className="text-xs text-red-500 mt-1">Selecione pelo menos uma unidade.</p>
                            )}
                        </div>
                    </div>
                </div>

                {/* Informações complementares */}
                <div className="bg-white dark:bg-slate-950 p-6 md:p-8 rounded-2xl shadow-sm border border-slate-200 dark:border-slate-800 transition-colors">
                    <h3 className="text-lg font-bold text-primary dark:text-blue-400 mb-6 flex items-center gap-2">
                        <FileText className="w-5 h-5" />
                        Informações complementares
                    </h3>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        <div>
                            <label className="block text-sm font-semibold text-slate-700 dark:text-slate-300 mb-2">Nome da mãe <span className="text-red-500">*</span></label>
                            <input required className="w-full p-3 border border-slate-300 dark:border-slate-700 rounded-xl bg-slate-50 dark:bg-slate-900 text-slate-900 dark:text-slate-100 focus:ring-2 focus:ring-primary focus:bg-white transition-all outline-none" placeholder="Digite o nome da mãe" value={formData.motherName || ''} onChange={e => handleInputChange('motherName', e.target.value)} />
                        </div>
                        <div>
                            <label className="block text-sm font-semibold text-slate-700 dark:text-slate-300 mb-2">Observações</label>
                            <textarea className="w-full p-3 border border-slate-300 dark:border-slate-700 rounded-xl bg-slate-50 dark:bg-slate-900 text-slate-900 dark:text-slate-100 focus:ring-2 focus:ring-primary focus:bg-white transition-all outline-none resize-none h-24" placeholder="Informações adicionais sobre o paciente (alergias, condições especiais, etc.)" value={formData.observations || ''} onChange={e => handleInputChange('observations', e.target.value)}></textarea>
                            <div className="text-right text-xs text-slate-400 mt-1">{(formData.observations?.length || 0)}/300</div>
                        </div>
                    </div>
                </div>

                {/* Ações */}
                <div className="flex flex-col-reverse sm:flex-row justify-center sm:justify-start gap-4 pt-4">
                    <p className="text-xs text-red-500 font-medium sm:hidden">* Campos de preenchimento obrigatório</p>
                    <div className="flex gap-4 w-full sm:w-auto ml-auto">
                        <button type="button" onClick={() => { resetForm(); setViewMode('list'); }} className="flex-1 sm:flex-none px-8 py-3 text-slate-700 dark:text-slate-300 font-bold border border-slate-300 dark:border-slate-700 hover:bg-slate-50 dark:hover:bg-slate-800 rounded-xl transition-colors">Limpar / Cancelar</button>
                        <button type="submit" className="flex-1 sm:flex-none px-8 py-3 bg-primary text-white font-bold rounded-xl hover:bg-primary-dark transition-colors shadow-sm flex items-center justify-center gap-2">
                            {editingId ? 'Atualizar cadastro' : 'Salvar cadastro'}
                        </button>
                    </div>
                </div>
                <p className="text-xs text-red-500 font-medium hidden sm:block">* Campos de preenchimento obrigatório</p>

            </div>

            {/* Coluna Direita (Sidebars) */}
            <div className="w-full lg:w-80 xl:w-96 space-y-6">
                
                {/* Orientações */}
                <div className="bg-slate-50 dark:bg-slate-900/50 p-6 rounded-2xl border border-blue-100 dark:border-slate-800 transition-colors">
                    <h4 className="font-bold text-primary dark:text-blue-400 flex items-center gap-2 mb-4">
                        <div className="w-6 h-6 rounded-full border-2 border-primary flex items-center justify-center text-xs font-bold">i</div>
                        Orientações para o cadastro
                    </h4>
                    <ul className="space-y-3 text-sm text-slate-700 dark:text-slate-300 list-disc pl-5 marker:text-slate-300 dark:marker:text-slate-600">
                        <li>Informe os dados com atenção para evitar erros no cadastro.</li>
                        <li>O Cartão do SUS é obrigatório para garantir a integração.</li>
                        <li>Verifique os dados antes de salvar.</li>
                    </ul>
                </div>

                {/* Validação */}
                <div className="bg-white dark:bg-slate-950 p-6 rounded-2xl shadow-sm border border-slate-200 dark:border-slate-800 transition-colors">
                    <h4 className="font-bold text-primary dark:text-blue-400 flex items-center gap-2 mb-6">
                        <div className="p-1.5 bg-blue-50 dark:bg-blue-900/30 rounded-lg"><UserIcon className="w-4 h-4" /></div>
                        Validação do cadastro
                    </h4>
                    
                    <div className="space-y-6">
                        <div className="flex gap-4">
                            <div className="mt-1"><div className="w-5 h-5 rounded-full border-2 border-slate-300 dark:border-slate-600"></div></div>
                            <div>
                                <p className="font-bold text-slate-800 dark:text-slate-200 text-sm">Documento apresentado</p>
                                <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">Confirme se o documento oficial foi apresentado.</p>
                            </div>
                        </div>
                        <div className="flex gap-4">
                            <div className="mt-1"><div className="w-5 h-5 rounded-full border-2 border-slate-300 dark:border-slate-600"></div></div>
                            <div>
                                <p className="font-bold text-slate-800 dark:text-slate-200 text-sm">SUS validado</p>
                                <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">O número do SUS será validado automaticamente.</p>
                            </div>
                        </div>
                        <div className="flex gap-4">
                            <div className="mt-1"><div className="w-5 h-5 rounded-full border-2 border-slate-300 dark:border-slate-600"></div></div>
                            <div>
                                <p className="font-bold text-slate-800 dark:text-slate-200 text-sm">Cadastro concluído</p>
                                <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">O paciente estará disponível para agendamento e atendimentos.</p>
                            </div>
                        </div>
                    </div>
                </div>

                {/* Recentes */}
                <div className="bg-white dark:bg-slate-950 p-6 rounded-2xl shadow-sm border border-slate-200 dark:border-slate-800 transition-colors">
                    <div className="flex justify-between items-center mb-6">
                        <h4 className="font-bold text-slate-800 dark:text-slate-200 flex items-center gap-2">
                            <UsersIcon className="w-5 h-5 text-slate-400 dark:text-slate-500" />
                            Pacientes recentes
                        </h4>
                    </div>
                    
                    <div className="space-y-4">
                        {patients.slice(0, 4).map((p, idx) => (
                            <div key={p.id} className="flex items-center gap-3">
                                <div className={`w-10 h-10 rounded-full flex items-center justify-center font-bold text-sm ${idx % 2 === 0 ? 'bg-green-100 text-green-700 dark:bg-emerald-900/30 dark:text-emerald-400' : 'bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400'}`}>
                                    {p.name.substring(0, 2).toUpperCase()}
                                </div>
                                <div className="flex-1 min-w-0">
                                    <p className="font-bold text-sm text-slate-800 dark:text-slate-200 truncate">{p.name}</p>
                                    <p className="text-xs text-slate-500 dark:text-slate-400">CPF: {p.cpf}</p>
                                </div>
                                <div className="text-right">
                                    <p className="text-xs text-slate-500 dark:text-slate-400">{new Date(p.birthDate).toLocaleDateString()}</p>
                                </div>
                            </div>
                        ))}
                        {patients.length === 0 && <p className="text-sm text-slate-500">Nenhum paciente cadastrado.</p>}
                    </div>

                    <button onClick={() => setViewMode('list')} className="w-full mt-6 py-3 border border-slate-200 dark:border-slate-700 rounded-xl text-primary font-bold hover:bg-slate-50 dark:hover:bg-slate-900 transition-colors">
                        Ver todos os pacientes →
                    </button>
                </div>
            </div>
        </form>
      </div>
    );
  }

  // LIST VIEW (Default)
  return (
    <div className="space-y-6 pb-12 animate-in fade-in duration-500">
      <div className="flex justify-between items-center">
        <div>
           <h2 className="text-2xl font-bold text-slate-800 dark:text-slate-100">Pacientes</h2>
           <p className="text-sm text-slate-500 dark:text-slate-400">Gerencie a base de cidadãos atendidos</p>
        </div>
        
        <div className="flex gap-2">
          <input type="file" accept=".csv" ref={fileInputRef} onChange={handleFileUpload} className="hidden" />
          <button 
            onClick={() => setIsImportModalOpen(true)}
            disabled={isImporting}
            className="flex items-center gap-2 bg-white dark:bg-slate-900 text-slate-700 dark:text-slate-300 border border-slate-300 dark:border-slate-700 px-4 py-2 rounded-lg hover:bg-slate-50 dark:hover:bg-slate-800 transition-colors disabled:opacity-50"
          >
            <Upload className="w-4 h-4" />
            {isImporting ? 'Importando...' : 'Importar CSV'}
          </button>
          <button 
            onClick={handleExport}
            className="flex items-center gap-2 bg-white dark:bg-slate-900 text-slate-700 dark:text-slate-300 border border-slate-300 dark:border-slate-700 px-4 py-2 rounded-lg hover:bg-slate-50 dark:hover:bg-slate-800 transition-colors"
          >
            <Download className="w-4 h-4" />
            Exportar CSV
          </button>
          <button 
            onClick={() => { resetForm(); setViewMode('form'); }}
            className="flex items-center gap-2 bg-primary text-white px-4 py-2 rounded-lg hover:bg-primary-dark transition-colors"
          >
            <Plus className="w-4 h-4" />
            Novo Paciente
          </button>
        </div>
      </div>

      <div className="bg-white dark:bg-slate-950 p-4 rounded-xl shadow-sm border border-slate-200 dark:border-slate-800 flex gap-2 transition-colors">
        <Search className="w-5 h-5 text-slate-400" />
        <input 
          type="text" 
          placeholder="Buscar por nome, CPF ou Cartão SUS..." 
          className="flex-1 outline-none text-slate-700 dark:text-slate-200 bg-transparent"
          value={searchTerm}
          onChange={(e) => setSearchTerm(e.target.value)}
        />
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {filteredPatients.map(patient => (
          <div key={patient.id} className="bg-white dark:bg-slate-950 p-6 rounded-2xl shadow-sm border border-slate-200 dark:border-slate-800 hover:border-primary dark:hover:border-primary transition-all cursor-pointer group relative flex flex-col">
            <button 
                onClick={(e) => { e.stopPropagation(); handleEdit(patient); }}
                className="absolute top-4 right-14 text-slate-400 hover:text-primary dark:hover:text-primary p-2 bg-slate-50 dark:bg-slate-900 rounded-lg opacity-0 group-hover:opacity-100 transition-all"
                title="Editar Paciente"
            >
                <Edit2 className="w-4 h-4" />
            </button>
            <button 
                onClick={(e) => { e.stopPropagation(); handleDelete(patient); }}
                className="absolute top-4 right-4 text-slate-400 hover:text-red-500 p-2 bg-slate-50 dark:bg-slate-900 rounded-lg opacity-0 group-hover:opacity-100 transition-all"
                title="Remover Paciente"
            >
                <Trash2 className="w-4 h-4" />
            </button>
            <div className="flex items-start gap-4 mb-4">
              <div className="w-12 h-12 rounded-full bg-slate-100 dark:bg-slate-900 flex items-center justify-center text-slate-500 dark:text-slate-400 group-hover:bg-primary/10 group-hover:text-primary transition-colors shrink-0">
                <UserIcon className="w-6 h-6" />
              </div>
              <div>
                <h3 className="font-bold text-lg text-slate-800 dark:text-slate-100 leading-tight mb-1">{patient.name}</h3>
                <div className="flex flex-col gap-0.5 text-xs text-slate-500 dark:text-slate-400 font-medium">
                   <span>CPF: {patient.cpf}</span>
                   {patient.susNumber && <span className="text-primary dark:text-blue-400">SUS: {patient.susNumber}</span>}
                </div>
              </div>
            </div>
            <div className="text-sm text-slate-600 dark:text-slate-400 space-y-2 pt-4 mt-auto border-t border-slate-100 dark:border-slate-800/50">
               <p className="flex items-center gap-2">
                 <FileText className="w-4 h-4 text-slate-400 dark:text-slate-500 shrink-0" />
                 Nasc: {new Date(patient.birthDate).toLocaleDateString()}
               </p>
               <p className="flex items-center gap-2">
                 <MapPin className="w-4 h-4 text-slate-400 dark:text-slate-500 shrink-0" />
                 <span className="truncate" title={patient.address ? `${patient.address}, ${patient.neighborhood}` : 'Endereço não cadastrado'}>
                     {patient.address ? `${patient.address}, ${patient.neighborhood}` : 'Endereço não cadastrado'}
                 </span>
               </p>
            </div>
          </div>
        ))}
        
        {filteredPatients.length === 0 && (
           <div className="col-span-full text-center py-12 bg-slate-50 dark:bg-slate-900/50 rounded-2xl border border-slate-200 dark:border-slate-800 border-dashed">
             <UserIcon className="w-12 h-12 text-slate-300 dark:text-slate-600 mx-auto mb-3" />
             <p className="text-slate-500 dark:text-slate-400 font-medium">Nenhum paciente encontrado para esta unidade.</p>
           </div>
        )}
      </div>

      {isImportModalOpen && (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-50 p-4">
          <div className="bg-white dark:bg-slate-900 rounded-2xl shadow-xl border border-slate-200 dark:border-slate-800 w-full max-w-lg overflow-hidden animate-in zoom-in-95 duration-200">
            <div className="p-6 border-b border-slate-100 dark:border-slate-800 flex justify-between items-center">
              <h3 className="text-xl font-bold text-slate-800 dark:text-slate-100 flex items-center gap-2">
                <Upload className="w-6 h-6 text-primary" /> Importar Pacientes
              </h3>
              <button onClick={() => setIsImportModalOpen(false)} className="text-slate-400 hover:text-slate-600 dark:hover:text-slate-200">
                <X className="w-5 h-5" />
              </button>
            </div>
            <div className="p-6 space-y-6">
              <div className="bg-blue-50 dark:bg-blue-900/20 border border-blue-100 dark:border-blue-900/50 p-4 rounded-xl flex gap-3">
                <AlertCircle className="w-5 h-5 text-primary shrink-0 mt-0.5" />
                <p className="text-sm text-blue-900 dark:text-blue-100 leading-relaxed">
                  Para importar pacientes em lote, você precisa de um arquivo CSV com as colunas na seguinte ordem: 
                  <strong> Nome, CPF, Cartão SUS, Data de Nascimento, Telefone, Endereço</strong>.
                </p>
              </div>

              <button 
                onClick={handleDownloadTemplate}
                className="w-full py-3 border-2 border-dashed border-slate-300 dark:border-slate-700 rounded-xl text-slate-600 dark:text-slate-400 font-semibold hover:border-primary hover:text-primary hover:bg-blue-50 dark:hover:bg-blue-900/20 transition-all flex justify-center items-center gap-2"
              >
                <Download className="w-5 h-5" /> Baixar Modelo CSV
              </button>
            </div>
            <div className="p-6 border-t border-slate-100 dark:border-slate-800 bg-slate-50 dark:bg-slate-900/50 flex gap-3">
              <button onClick={() => setIsImportModalOpen(false)} className="flex-1 py-3 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-600 dark:text-slate-300 font-bold rounded-xl hover:bg-slate-50 dark:hover:bg-slate-700 transition-colors">
                Cancelar
              </button>
              <button 
                onClick={() => fileInputRef.current?.click()}
                className="flex-1 py-3 bg-primary hover:bg-primary-dark text-white font-bold rounded-xl transition-colors flex justify-center items-center gap-2"
              >
                <Upload className="w-5 h-5" /> Selecionar Arquivo
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};